name: Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 15 * * 6'

jobs:
  analyze:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialize
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Analyse
      uses: github/codeql-action/analyze@v1
